name = "tcg-repricer"
client_id = "SHOPIFY_CLIENT_ID"
application_url = "https://your-app-url.com"
embedded = true

[access_scopes]
# Define required OAuth scopes
scopes = "write_products,read_products,write_inventory,read_inventory"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback",
  "https://your-app-url.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false